name: Build akmenu-next

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:20241104
    name: Build with Docker using devkitARM (pre-calico)

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Update packages
        run: |
          sudo -n apt-get update
          sudo -n apt-get upgrade -y fakeroot zip p7zip-full

      - name: Silence all git safe directory warnings
        run: git config --system --add safe.directory '*'

      - name: Set workspace permissions
        run: chmod 777 -R "$GITHUB_WORKSPACE"

      - name: Build akmenu-next
        run: |
          make -j$(nproc)

      - name: Run package script
        run: |
          cd package
          chmod +x package.sh
          ./package.sh

      - name: Upload akmenu-next-flashcart
        uses: actions/upload-artifact@v4
        with:
          name: akmenu-next-flashcart
          path: package/akmenu-next-flashcart.zip

      - name: Upload akmenu-next-dsi
        uses: actions/upload-artifact@v4
        with:
          name: akmenu-next-dsi
          path: package/akmenu-next-dsi.zip

      - name: Upload akmenu-next-3ds
        uses: actions/upload-artifact@v4
        with:
          name: akmenu-next-3ds
          path: package/akmenu-next-3ds.zip
